
settings[SETTINGS_DIFFICULTY] = 1.0;
settings[SETTINGS_LIFEFORM_SHADOW] = false;
settings[SETTINGS_MAP_SHADOW] = false;
settings[SETTINGS_SCROLL_SPEED] = 1.0;
global.scrollSpeed = 1;

settingsType[SETTINGS_DIFFICULTY] = SETTINGS_TYPE_DECIMAL;
settingsType[SETTINGS_LIFEFORM_SHADOW] = SETTINGS_TYPE_BOOLEAN;
settingsType[SETTINGS_MAP_SHADOW] = SETTINGS_TYPE_BOOLEAN;
settingsType[SETTINGS_SCROLL_SPEED] = SETTINGS_TYPE_DECIMAL;