if(statsCurrent[STATS_PHYSICAL, STATS_PHYSICAL_ENERGY] + recoverEnergyAmount < statsMax[STATS_PHYSICAL, STATS_PHYSICAL_ENERGY]){
    statsCurrent[STATS_PHYSICAL, STATS_PHYSICAL_ENERGY] += recoverEnergyAmount;
}
else{
	statsCurrent[STATS_PHYSICAL, STATS_PHYSICAL_ENERGY] = statsMax[STATS_PHYSICAL, STATS_PHYSICAL_ENERGY];
}