#macro LEVEL_CAP 256
#macro EXPERIENCE_MULTIPLIER 2
#macro STATS_MULTIPLIER 5
#macro STATS_HEALTH_MULTIPLIER 5
#macro STATS_ENERGY_MULTIPLIER 10
#macro VAULT_MAX 16

#macro ALLEGIANCE_BLUE 0
#macro ALLEGIANCE_RED 1
#macro ALLEGIANCE_NEUTRAL 2
#macro ALLEGIANCE_ANIMAL 3
#macro ALLEGIANCE_MAX 4

#macro ATTACK_MELEE 0
#macro ATTACK_RANGE 1
#macro ATTACKS_MAX 8

#macro BLOCK 2
#macro DOWN 3

#macro EQUIPMENT_STATS_DAMAGE 0
#macro EQUIPMENT_STATS_RANGE 1
#macro EQUIPMENT_STATS_DEFENCE 2
#macro EQUIPMENT_STATS_TYPE 3
#macro EQUIPMENT_STATS_TOOL_TYPE 4
#macro EQUIPMENT_STATS_MAX 5

#macro EQUIPMENT_TYPE_WEAPON 0
#macro EQUIPMENT_TYPE_OFFHAND 1
#macro EQUIPMENT_TYPE_MAX 2

#macro FACE_DOWN 6
#macro FACE_DOWNLEFT 5
#macro FACE_DOWNRIGHT 7
#macro FACE_LEFT 4
#macro FACE_RIGHT 0
#macro FACE_UP 2
#macro FACE_UPPERLEFT 3
#macro FACE_UPPERRIGHT 1

#macro FIXTURE_COLLISION_LIFEFORM -1

#macro INVENTORY_MAX 16

#macro ITEM_STATS_NAME 0
#macro ITEM_STATS_WEIGHT 1
#macro ITEM_STATS_TYPE 2
#macro ITEM_STATS_VALUE 3
#macro ITEM_STATS_DROP_PERCENTAGE 4
#macro ITEM_STATS_MAX 5

#macro ITEM_TYPE_CONSUMABLE 0
#macro ITEM_TYPE_EQUIPMENT 1
#macro ITEM_TYPE_MAX 2

#macro LEFT 2
#macro MAX_NPCS 100
#macro MOVEMENT_ACCURACY 5
#macro OFFHAND 1
#macro RIGHT 0

#macro STATS_COMMANDING_DISCIPLINE 1
#macro STATS_COMMANDING_INSPIRATION 0
#macro STATS_COMMANDING_MAX 2
#macro STATS_COMMANDING 2

#macro STATS_INTELLIGENCE_INTERPRETATION 1
#macro STATS_INTELLIGENCE_LANGUAGES 0
#macro STATS_INTELLIGENCE_MAX 2
#macro STATS_INTELLIGENCE 3

#macro STATS_MAX 4

#macro STATS_PHYSICAL_ENERGY 2
#macro STATS_PHYSICAL_HEALTH 1
#macro STATS_PHYSICAL_MAX 3
#macro STATS_PHYSICAL_STRENGTH 0
#macro STATS_PHYSICAL 0

#macro STATS_TOOLS_BLADES 0
#macro STATS_TOOLS_BOWS 1
#macro STATS_TOOLS_SHIELDS 2
#macro STATS_TOOLS_BLUNTS 3
#macro STATS_TOOLS_MAX 4
#macro STATS_TOOLS 1

#macro STRING_GAME_TITLE "Conquests of Relnor"

#macro TRIGGER_ATTACK 0
#macro TRIGGER_DASH 1
#macro TRIGGER_ESC 2
#macro TRIGGER_FORMATION 3
#macro TRIGGER_ENGAGE 4
#macro TRIGGER_ENGAGE_DISABLE 5
#macro TRIGGER_MAGIC 6
#macro TRIGGER_MAGIC_CYCLE 7
#macro TRIGGER_ATTACK_CYCLE 8
#macro TRIGGERS_MAX 9

#macro UP 1
#macro WEAPON_TYPE_MAGIC 2
#macro WEAPON_TYPE_MELEE 0
#macro WEAPON_TYPE_RANGE 1
#macro WEAPON 0


#macro ORIGIN_NONE 0
#macro ORIGIN_RELNOR 1
#macro ORIGIN_FORT_FLORE 2
#macro ORIGIN_PORT_ORDINANCE 3
#macro ORIGIN_POSHEL 4
#macro ORIGIN_DEVIAH 5
#macro ORIGIN_FORT_PLATZ 6
#macro ORIGIN_ECKHART 7
#macro ORIGIN_LETZSTED 8
#macro ORIGIN_CROSSHEIM 9
#macro ORIGIN_TOSHEL 10
#macro ORIGIN_PORT_JANISH 11
#macro ORIGIN_FORT_TEEK 12
#macro ORIGIN_SOSHEM 13
#macro ORIGIN_BLAVISH 14
#macro ORIGIN_FRELISH 15
#macro ORIGIN_AGNOR 16

#macro REGION_NONE 0
#macro REGION_RELN 1
#macro REGION_FRELIK 2
#macro REGION_STONETREE 3
#macro REGION_TRELISH 4
#macro REGION_TRESPONTE 5
#macro REGION_LELITH 6
#macro REGION_PASS_OF_KROLN 7

#macro SHOP_ITEMS_MAX 16

#macro MAX 2147482200

#macro LIGHT_DIRECTION_STANDARD 0
#macro LIGHT_DIRECTION_UP 1
#macro LIGHT_DIRECTION_DOWN 2
#macro LIGHT_DIRECTION_LEFT 3
#macro LIGHT_DIRECTION_RIGHT 4

#macro SPELL_MAX 16