// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_damage_parent
global.__objectDepths[1] = 0; // obj_damage_melee_small
global.__objectDepths[2] = 0; // obj_damage_melee_medium
global.__objectDepths[3] = 0; // obj_damage_range_projectile
global.__objectDepths[4] = 0; // obj_damage_projectile_arrow
global.__objectDepths[5] = 0; // obj_equipment_bows_parent
global.__objectDepths[6] = 0; // obj_equipment_weapon_parent
global.__objectDepths[7] = 0; // obj_equipment_sword_parent
global.__objectDepths[8] = 0; // obj_equipment_iron_shield_parent
global.__objectDepths[9] = 0; // obj_inventory_equipment_offhand_parent
global.__objectDepths[10] = 0; // obj_inventory_equipment_parent
global.__objectDepths[11] = 0; // obj_player_global
global.__objectDepths[12] = 0; // obj_inventory_item_parent
global.__objectDepths[13] = 0; // obj_player_view
global.__objectDepths[14] = 0; // obj_player_select_box
global.__objectDepths[15] = 0; // obj_player_command_module
global.__objectDepths[16] = 0; // obj_player
global.__objectDepths[17] = 0; // obj_npc_blue_cavalry
global.__objectDepths[18] = 0; // obj_npc_blue_archer
global.__objectDepths[19] = 0; // obj_player_command_square_preview
global.__objectDepths[20] = 0; // obj_npc_red_cavalry
global.__objectDepths[21] = 0; // obj_npc_red_soldier
global.__objectDepths[22] = 0; // obj_npc_blue_soldier
global.__objectDepths[23] = 0; // obj_npc_Commandable_Npc
global.__objectDepths[24] = 0; // obj_npc_Parent
global.__objectDepths[25] = 0; // obj_npc_red_archer
global.__objectDepths[26] = 0; // obj_Lifeform_Parent
global.__objectDepths[27] = 0; // obj_Lifeform_Dash_Effect
global.__objectDepths[28] = 0; // obj_lifeform_body
global.__objectDepths[29] = 0; // obj_test_wall
global.__objectDepths[30] = 0; // obj_global_command_selection
global.__objectDepths[31] = 0; // obj_ui_chat
global.__objectDepths[32] = 0; // obj_ui_energy_bar
global.__objectDepths[33] = 0; // obj_ui_health_bar
global.__objectDepths[34] = 0; // obj_ui_draw_parent
global.__objectDepths[35] = 0; // obj_ui_party_inventory_item_info
global.__objectDepths[36] = 0; // obj_ui_party_inventory_row
global.__objectDepths[37] = 0; // obj_ui_button_information
global.__objectDepths[38] = 0; // obj_ui_button
global.__objectDepths[39] = 0; // obj_ui_button_mouse_listener
global.__objectDepths[40] = 0; // obj_ui_icon_parent
global.__objectDepths[41] = 0; // obj_ui_clickable_parent
global.__objectDepths[42] = 0; // obj_ui_party_character_panel
global.__objectDepths[43] = 0; // obj_ui_font
global.__objectDepths[44] = 0; // obj_ui_menu_container
global.__objectDepths[45] = 0; // obj_npc_old_man_01
global.__objectDepths[46] = 0; // obj_ui_line
global.__objectDepths[47] = 0; // obj_array
global.__objectDepths[48] = 0; // obj_damage_display_amount
global.__objectDepths[49] = 0; // obj_ui_notification
global.__objectDepths[50] = 0; // obj_map_door_invisible
global.__objectDepths[51] = 0; // obj_map_door_wooden_2
global.__objectDepths[52] = 0; // obj_map_door_wooden_3
global.__objectDepths[53] = 0; // obj_map_door_wooden_1
global.__objectDepths[54] = 0; // obj_map_door_parent
global.__objectDepths[55] = 0; // obj_map_door_wooden_4
global.__objectDepths[56] = 0; // obj_map_door_wooden_5
global.__objectDepths[57] = 0; // obj_unwalkable
global.__objectDepths[58] = 0; // obj_map_unwalkable_medium
global.__objectDepths[59] = 0; // obj_map_initialize
global.__objectDepths[60] = 0; // obj_map_clutter_table_01
global.__objectDepths[61] = 0; // obj_map_clutter_stool_02
global.__objectDepths[62] = 0; // obj_map_clutter_table_04
global.__objectDepths[63] = 0; // obj_map_clutter_counter_01
global.__objectDepths[64] = 0; // obj_map_foreground_black
global.__objectDepths[65] = 0; // obj_map_clutter_counter_01_end
global.__objectDepths[66] = 0; // obj_map_clutter_bottle_01
global.__objectDepths[67] = 0; // obj_map_clutter_stool_01
global.__objectDepths[68] = 0; // obj_map_clutter_bottle_02
global.__objectDepths[69] = 0; // obj_map_clutter_bottle_03
global.__objectDepths[70] = 0; // obj_map_clutter_bottle_04
global.__objectDepths[71] = 0; // flower01
global.__objectDepths[72] = 0; // obj_map_clutter_drink_01
global.__objectDepths[73] = 0; // flower_e
global.__objectDepths[74] = 0; // chest_01_c
global.__objectDepths[75] = 0; // stand_02
global.__objectDepths[76] = 0; // obj_map_clutter_light_candle_01_U
global.__objectDepths[77] = 0; // stand_01
global.__objectDepths[78] = 0; // torch_01_u_R
global.__objectDepths[79] = 0; // torch_01_u_L
global.__objectDepths[80] = 0; // torch_01_u_C
global.__objectDepths[81] = 0; // obj_map_solid_parent
global.__objectDepths[82] = 0; // obj_map_foreground
global.__objectDepths[83] = 0; // obj_map_weapon_sword_02_s01
global.__objectDepths[84] = 0; // obj_map_clutter_table_02
global.__objectDepths[85] = 0; // obj_map_clutter_drink02
global.__objectDepths[86] = 0; // obj_map_clutter_table_03
global.__objectDepths[87] = 0; // empty


global.__objectNames[0] = "obj_damage_parent";
global.__objectNames[1] = "obj_damage_melee_small";
global.__objectNames[2] = "obj_damage_melee_medium";
global.__objectNames[3] = "obj_damage_range_projectile";
global.__objectNames[4] = "obj_damage_projectile_arrow";
global.__objectNames[5] = "obj_equipment_bows_parent";
global.__objectNames[6] = "obj_equipment_weapon_parent";
global.__objectNames[7] = "obj_equipment_sword_parent";
global.__objectNames[8] = "obj_equipment_iron_shield_parent";
global.__objectNames[9] = "obj_inventory_equipment_offhand_parent";
global.__objectNames[10] = "obj_inventory_equipment_parent";
global.__objectNames[11] = "obj_player_global";
global.__objectNames[12] = "obj_inventory_item_parent";
global.__objectNames[13] = "obj_player_view";
global.__objectNames[14] = "obj_player_select_box";
global.__objectNames[15] = "obj_player_command_module";
global.__objectNames[16] = "obj_player";
global.__objectNames[17] = "obj_npc_blue_cavalry";
global.__objectNames[18] = "obj_npc_blue_archer";
global.__objectNames[19] = "obj_player_command_square_preview";
global.__objectNames[20] = "obj_npc_red_cavalry";
global.__objectNames[21] = "obj_npc_red_soldier";
global.__objectNames[22] = "obj_npc_blue_soldier";
global.__objectNames[23] = "obj_npc_Commandable_Npc";
global.__objectNames[24] = "obj_npc_Parent";
global.__objectNames[25] = "obj_npc_red_archer";
global.__objectNames[26] = "obj_Lifeform_Parent";
global.__objectNames[27] = "obj_Lifeform_Dash_Effect";
global.__objectNames[28] = "obj_lifeform_body";
global.__objectNames[29] = "obj_test_wall";
global.__objectNames[30] = "obj_global_command_selection";
global.__objectNames[31] = "obj_ui_chat";
global.__objectNames[32] = "obj_ui_energy_bar";
global.__objectNames[33] = "obj_ui_health_bar";
global.__objectNames[34] = "obj_ui_draw_parent";
global.__objectNames[35] = "obj_ui_party_inventory_item_info";
global.__objectNames[36] = "obj_ui_party_inventory_row";
global.__objectNames[37] = "obj_ui_button_information";
global.__objectNames[38] = "obj_ui_button";
global.__objectNames[39] = "obj_ui_button_mouse_listener";
global.__objectNames[40] = "obj_ui_icon_parent";
global.__objectNames[41] = "obj_ui_clickable_parent";
global.__objectNames[42] = "obj_ui_party_character_panel";
global.__objectNames[43] = "obj_ui_font";
global.__objectNames[44] = "obj_ui_menu_container";
global.__objectNames[45] = "obj_npc_old_man_01";
global.__objectNames[46] = "obj_ui_line";
global.__objectNames[47] = "obj_array";
global.__objectNames[48] = "obj_damage_display_amount";
global.__objectNames[49] = "obj_ui_notification";
global.__objectNames[50] = "obj_map_door_invisible";
global.__objectNames[51] = "obj_map_door_wooden_2";
global.__objectNames[52] = "obj_map_door_wooden_3";
global.__objectNames[53] = "obj_map_door_wooden_1";
global.__objectNames[54] = "obj_map_door_parent";
global.__objectNames[55] = "obj_map_door_wooden_4";
global.__objectNames[56] = "obj_map_door_wooden_5";
global.__objectNames[57] = "obj_unwalkable";
global.__objectNames[58] = "obj_map_unwalkable_medium";
global.__objectNames[59] = "obj_map_initialize";
global.__objectNames[60] = "obj_map_clutter_table_01";
global.__objectNames[61] = "obj_map_clutter_stool_02";
global.__objectNames[62] = "obj_map_clutter_table_04";
global.__objectNames[63] = "obj_map_clutter_counter_01";
global.__objectNames[64] = "obj_map_foreground_black";
global.__objectNames[65] = "obj_map_clutter_counter_01_end";
global.__objectNames[66] = "obj_map_clutter_bottle_01";
global.__objectNames[67] = "obj_map_clutter_stool_01";
global.__objectNames[68] = "obj_map_clutter_bottle_02";
global.__objectNames[69] = "obj_map_clutter_bottle_03";
global.__objectNames[70] = "obj_map_clutter_bottle_04";
global.__objectNames[71] = "flower01";
global.__objectNames[72] = "obj_map_clutter_drink_01";
global.__objectNames[73] = "flower_e";
global.__objectNames[74] = "chest_01_c";
global.__objectNames[75] = "stand_02";
global.__objectNames[76] = "obj_map_clutter_light_candle_01_U";
global.__objectNames[77] = "stand_01";
global.__objectNames[78] = "torch_01_u_R";
global.__objectNames[79] = "torch_01_u_L";
global.__objectNames[80] = "torch_01_u_C";
global.__objectNames[81] = "obj_map_solid_parent";
global.__objectNames[82] = "obj_map_foreground";
global.__objectNames[83] = "obj_map_weapon_sword_02_s01";
global.__objectNames[84] = "obj_map_clutter_table_02";
global.__objectNames[85] = "obj_map_clutter_drink02";
global.__objectNames[86] = "obj_map_clutter_table_03";
global.__objectNames[87] = "empty";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for